# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter-service.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("greeter-service.proto", :syntax => :proto3) do
    add_message "helloworld.HelloRequest" do
      optional :name, :string, 1
    end
    add_message "helloworld.HelloResponse" do
      optional :message, :string, 1
    end
  end
end

module Helloworld
  HelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.HelloRequest").msgclass
  HelloResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.HelloResponse").msgclass
end
